# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-05 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeTeam_score', models.CharField(max_length=20, verbose_name='主队进球')),
                ('VisitingTeams_score', models.CharField(max_length=20, verbose_name='客队进球')),
                ('time', models.DateTimeField(verbose_name='比赛日期')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10, verbose_name='小组')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=20, verbose_name='进球')),
                ('lost', models.CharField(max_length=20, verbose_name='失球')),
                ('goal_difference', models.CharField(max_length=20, verbose_name='净胜球')),
                ('score', models.CharField(max_length=20, verbose_name='积分')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.Groups')),
            ],
            options={
                'ordering': ['-score', '-goal_difference', '-team'],
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30, verbose_name='球队')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.Groups')),
            ],
        ),
        migrations.AddField(
            model_name='scores',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.Teams'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='HomeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='HomeTeam', to='index.Teams'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='VisitingTeams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='VisitingTeam', to='index.Teams'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.Groups'),
        ),
    ]
